/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-container": "#003366",
        "outline-variant": "#c3c6d1",
        "surface-bright": "#f7f9fc",
        "on-surface-variant": "#43474f",
        "primary": "#001e40",
        "inverse-surface": "#2d3133",
        "surface-container-highest": "#e0e3e6",
        "surface-container-low": "#f2f4f7",
        "on-primary-fixed-variant": "#1f477b",
        "on-secondary": "#ffffff",
        "tertiary-container": "#592300",
        "on-secondary-fixed-variant": "#584400",
        "tertiary-fixed": "#ffdbca",
        "on-background": "#191c1e",
        "on-primary-fixed": "#001b3c",
        "surface-tint": "#3a5f94",
        "outline": "#737780",
        "background": "#f7f9fc",
        "primary-fixed": "#d5e3ff",
        "on-error": "#ffffff",
        "tertiary": "#381300",
        "surface-variant": "#e0e3e6",
        "on-tertiary-fixed-variant": "#723610",
        "on-secondary-fixed": "#241a00",
        "inverse-on-surface": "#eff1f4",
        "surface": "#f7f9fc",
        "error": "#ba1a1a",
        "on-surface": "#191c1e",
        "on-tertiary": "#ffffff",
        "secondary": "#745b00",
        "on-primary-container": "#799dd6",
        "on-tertiary-fixed": "#341100",
        "on-primary": "#ffffff",
        "inverse-primary": "#a7c8ff",
        "primary-fixed-dim": "#a7c8ff",
        "surface-dim": "#d8dadd",
        "secondary-container": "#fecb00",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#ffb690",
        "error-container": "#ffdad6",
        "surface-container-high": "#e6e8eb",
        "on-secondary-container": "#6e5700",
        "surface-container": "#eceef1",
        "secondary-fixed-dim": "#f1c100",
        "on-tertiary-container": "#d8885c",
        "secondary-fixed": "#ffe08b"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "card": "24px",
        "full": "9999px"
      },
      spacing: {
        "md": "16px",
        "lg": "24px",
        "sm": "12px",
        "xl": "32px",
        "base": "4px",
        "gutter-mobile": "16px",
        "xs": "8px",
        "margin-mobile": "20px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
